<a href="https://colab.research.google.com/github/Efe272/Yapayzeka/blob/main/Python-Numpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# 1) (10,15,30,45,60) değerlerine sahip numpy dizisi oluştur.

In [4]:
result=np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

#2) 5-15 arasındaki sayılarla bir dizi oluştur.

In [7]:
result=np.arange(5,15)
result


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#3)(50-100 arasında 5 er 5 er bir dizi oluştur.


In [8]:
result=np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

#4)(10- elemanlı sıfırdan oluşan bir dizi oluşturunuz.


In [10]:
result=np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#5 (10-elemanlı birlerden oluşan bir dizi oluşturunuz.


In [11]:
result=np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#6 (0-100 arasında eşit aralıklı 5 sayı üretin

In [12]:
result=np.linspace(0,100,5)
result

array([  0.,  25.,  50.,  75., 100.])

#7 (10-30 arasında rastgele 5 tane tamsayı üretin

In [13]:
result=np.random.randint(10,30,5)
result

array([24, 24, 21, 11, 27])

#8 ([-1 ile 1 ]arasında 10 adet sayı üretin.


In [14]:
result=np.random.randn(10)
result

array([ 2.21771727, -0.39456538,  0.05741656,  1.1100746 ,  1.7317899 ,
        0.42491241, -0.46703848, -0.18880169, -0.52536293, -0.70335551])

#9(3*5 boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

In [15]:
result=np.random.randint(10,50,15).reshape(3,5)
result

array([[12, 45, 20, 27, 22],
       [44, 40, 13, 49, 14],
       [49, 44, 24, 44, 37]])

#10 (üretilen matrisin  satır ve sütun sayıları toplamlarını hesaplayınız ?

In [16]:
matris = np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis =1)
colTotal = matris.sum(axis = 0)
print(rowTotal)
print(colTotal)

[130 155 146]
[103  68  63  93 104]


#11 ( Üretilen matrisin en büyük,en küçük ve ortalaması nedir ?)

In [17]:
result = matris.max()
result = matris.min()
result = matris.mean()
result

28.733333333333334

#12(Üretilen matrisin en büyük değerinin indeksi kaçtır ?)

In [18]:
result = matris.argmax()
result = matris.argmin()
result

11

#13 (10-20 arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz

In [19]:
arr= np.arange (10,20)
print(arr)
resılt =arr[0:]
result

[10 11 12 13 14 15 16 17 18 19]


11

#14 (Üretilen dizinin elemanlarını tersten yazdırın.)

In [20]:
result=arr[::]
result

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#15(üretilen dizinin elemanlarını tersten yazdırın)

In [21]:
result=matris[0]
result

array([27, 18, 21, 29, 35])

#16(Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir?

In [22]:
result = matris[1,2]
result

13

#17(üretilen matrisin tüm satırlardaki ilk elemanı seçiniz)

In [23]:
result = matris[:,1]

#18(üretilen matrisin her bir elemanının karesini alınız

In [24]:
result = matris**2

#19 üretilen matris elemanlarının hangisi pozitif çift sayıdır? aralığı (-50,+50) arasında yapınız.

In [25]:
result = matris[matris %2==0]
print(result)

[18 36 40 40 10 28]
